extends:
  - airbnb
  - prettier
plugins:
  - react
  - jsx-a11y
  - import
rules:
  consistent-return:
    - off
  import/no-unresolved:
    - 2
    -
      ignore:
        - pouchdb
  import/no-extraneous-dependencies:
    - off
  import/extensions:
    - error
    - never #ignorePackages
  no-restricted-syntax:
    - off
  no-await-in-loop:
    - off
  no-empty:
    - error
    -
      allowEmptyCatch: true
  no-shadow:
    - off
  # For optional catch binding, until https://github.com/eslint/eslint/pull/9613 is merged.
  no-shadow-restricted-names:
    - off
  no-underscore-dangle:
    - off
  no-unused-expressions:
    - off
  react/forbid-prop-types:
    - off
  react/jsx-filename-extension:
    - off
  react/prop-types:
    - 2
    -
      skipUndeclared: true
  react/react-in-jsx-scope:
    - off
  react/no-children-prop:
    - off
globals:
  document: true
  fetch: true
parser: babel-eslint
env:
  jest: true
  browser: true
# parserOptions:
#   nullishCoalescingOperator: true
